### ISSUE TITLE
Missing features for license options

### ISSUE THREAD

**Issue by thvd** [forcedotcom/schemas#10]
In the project-scratch-def.schema.json there is missing the definition of the availability to add 

```json

    "features": ["PartnerCommunity", "CustomerCommunityPlusLogin"],

```

Which enables you to enable the partner community features on a Enterprise scratch org.

Also check out this post on Stackoverflow: https://salesforce.stackexchange.com/questions/247626/customer-community-license-in-an-enterprise-edition-scratch-org/274829

**Comment by stevebingsoo** [comment]
please add this to the documentation.  I wasted a ton of time before I came across the stackexchange post

**Comment by joeythomaschaske** [comment]
2025 and I still wasted 3 hours just to find this
