### ISSUE TITLE
Update Schema for project-scratch-def.json

### ISSUE THREAD

**Issue by JohnGordos-Evolve** [forcedotcom/schemas#30]
### Summary

In Winter '21, FieldService requires a quantity to be added, but it doesn't look like the file's schema was updated.
https://releasenotes.docs.salesforce.com/en-us/winter21/release-notes/rn_scratch_org_features.htm

### Steps To Reproduce:

1.  Create a new, standard Salesforce project.
2. Attempt to enable FieldService in the project-scratch-def with any quantity.
3. An error is displayed, indicating the entry we added doesn't match the schema's pattern.
![image](https://user-images.githubusercontent.com/63373215/106517706-17142400-6496-11eb-8adb-f7ded8621308.png)

### Expected result

The error wouldn't be displayed.

### Actual result

The error is displayed, which might confuse new developers.  We're still able to save and create a scratch org from the file.

**Comment by lcampos** [comment]
Hi @JohnGordos-Evolve , thanks for opening this issue. We've updated these definitions as part of PR #32 and it's now published under version 1.0.4 on npm. This will also be part of the next release of the Salesforce extensions for VSCode.
